GET http://localhost:5031

###
GET http://localhost:5031/users

###
GET http://localhost:5031/users/2

###
POST http://localhost:5031/users
Content-Type: application/json

{
    "FullName": "Darwin",
    "Email": "Darwin@example.com",
    "Phone": "123-456-7890",
    "Password": "password123",
    "Role": "Client",
    "Status": "Active"
}

###
PUT http://localhost:5031/users/2
Content-Type: application/json

{
    "EmployeeId": "TL-002",
    "FullName": "Alice Smith",
    "Email": "alice.smith@example.com",
    "Phone": "987-654-3210",
    "Password": "newpassword456",

    "Role": "Admin",
    "Status": "Active"
}

###
DELETE http://localhost:5031/users/2


###
#AUTH ENDPOINTS
POST http://localhost:5031/api/auth/login
Content-Type: application/json

{
    "identifier": "ML-8842",
    "password": "P@ssw0rd123"
}

###
//refresh endpoint
POST http://localhost:5031/api/auth/refresh
Content-Type: application/json

{
    "refreshToken": "TOKEN_FROM_LOGIN"
}

###
#logout
POST http://localhost:5031/api/auth/logout
Authorization: Bearer ACCESS_TOKEN_
Content-Type: application/json

{
    "refreshToken": "REFRESH_TOKEN"
}